spring.application.name=Acueducto-Proyecto
spring.datasource.url=jdbc:mysql://localhost:3306/Acueducto_Proyecto
spring.datasource.username=root
spring.datasource.password=colorado.123//
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
